import React, { useState } from "react";
import {
  FolderGit2,
  Check,
  RotateCcw,
  Download,
  CheckCircle2,
  Archive,
  Copy,
  CheckCheck,
  Layers,
  Terminal,
  Cpu,
  FileSpreadsheet,
  Cable,
  Wrench,
  FileText,
  ExternalLink,
  QrCode,
} from "lucide-react";
import { HardwareProject, TabKey } from "../types";
import JSZip from "jszip";
import confetti from "canvas-confetti";

interface EngineeringWorkbenchProps {
  project: HardwareProject;
  onBackToWorkbench: () => void;
  onSelectHighlightKey?: (key?: string) => void;
}

export const EngineeringWorkbench: React.FC<EngineeringWorkbenchProps> = ({
  project,
  onBackToWorkbench,
  onSelectHighlightKey,
}) => {
  const [activeTab, setActiveTab] = useState<TabKey>("bom");
  const [isExporting, setIsExporting] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const [highlightedRow, setHighlightedRow] = useState<string | null>(null);

  const totalPrice = project.components.reduce((sum, c) => sum + c.price * c.quantity, 0);

  const handleCopyCode = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleExportZip = async () => {
    try {
      setIsExporting(true);
      const zip = new JSZip();

      // 1. README.md
      const readmeContent = `# ${project.title} (${project.version}) - 工程交付包
> 云端造物 (Cloud Maker / Design by Result) 自动创成硬件项目工程包

## 项目概述
- **名称**: ${project.title}
- **版本**: ${project.version}
- **简介**: ${project.desc}
- **主控平台**: ${project.specs.mcu}
- **预估单价**: ￥${totalPrice.toFixed(2)}
- **外形尺寸**: ${project.specs.dimensions}
- **整机重量**: ${project.specs.weight}
- **电池供电**: ${project.specs.battery} (${project.specs.powerSupply})
- **无线互联**: ${project.specs.connectivity}

---

## 硬件核心能力
${project.abilities.map((a, i) => `${i + 1}. **${a.title}**: ${a.desc} (${a.implementation})`).join("\n")}

---

## 快速烧录固件
\`\`\`bash
${project.instructions.step1Flash}
\`\`\`

## 首次配网与云端测试
1. ${project.instructions.wifiConfig}
2. ${project.instructions.cloudTesting}
`;
      zip.file("README.md", readmeContent);

      // 2. BOM.csv
      let bomCsv = "编号,模块名称,规格型号,用量,接口/总线,预估单价(RMB),功能说明\n";
      project.components.forEach((c) => {
        bomCsv += `"${c.id}","${c.name}","${c.model}","${c.quantity}","${c.bus}","¥${c.price.toFixed(2)}","${c.function}"\n`;
      });
      zip.file("BOM_清单.csv", "\uFEFF" + bomCsv);

      // 3. WIRING_PINOUT.json
      zip.file("wiring_pinout.json", JSON.stringify(project.wiring, null, 2));

      // 4. FLASH SCRIPTS
      zip.file(
        "flash_firmware.sh",
        `#!/bin/bash\necho "Flashing ${project.title} firmware..."\n${project.instructions.step1Flash}\necho "Flash completed!"`
      );
      zip.file(
        "flash_firmware.bat",
        `@echo off\necho Flashing ${project.title} firmware...\n${project.instructions.step1Flash}\necho Flash completed!\npause`
      );

      // 5. C Header Config for ESP-IDF / Arduino
      const cHeader = `/*
 * Auto-generated by Cloud Maker for ${project.title} ${project.version}
 */
#pragma once

#define DEVICE_NAME "${project.title}"
#define HARDWARE_VERSION "${project.version}"
#define MCU_TYPE "${project.specs.mcu}"

// I2C Pin Configuration
#define PIN_I2C_SDA 4
#define PIN_I2C_SCL 5

// I2S Audio Configuration
#define PIN_I2S_BCLK 15
#define PIN_I2S_LRC  16
#define PIN_I2S_DIN  17
#define PIN_I2S_MIC_SCK 2
#define PIN_I2S_MIC_SD  1

// Cloud Configuration
#define DEFAULT_AP_SSID "CloudMaker-AP"
#define CLOUD_WS_ENDPOINT "wss://vcloud.maker.ai/device/stream"
`;
      zip.file("firmware_config.h", cHeader);

      // 6. 3D MECH SPEC
      const mechSpec = `3D PRINTING SPECIFICATIONS & ASSEMBLY GUIDE
Project: ${project.title} (${project.version})
Dimensions: ${project.specs.dimensions}

Materials & Slicing:
- Recommended Filament: PLA / PETG / SLA Resin
- Layer Height: 0.16mm - 0.20mm
- Infill: 20% - 30% Gyroid
- Wall Perimeters: 3 loops
- Support: Tree support enabled for overhangs > 50°

Parts List:
${project.mechParts.map((p) => `- ${p.name}: ${p.material} | ${p.method} | x${p.count}`).join("\n")}

Assembly Instructions:
${project.instructions.assemblyGuide}
`;
      zip.file("cad_3d_specs.txt", mechSpec);

      // Generate blob
      const content = await zip.generateAsync({ type: "blob" });

      // Trigger browser download
      const url = URL.createObjectURL(content);
      const link = document.createElement("a");
      link.href = url;
      link.download = `${project.title}_${project.version}_完整工程包.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      // Celebrate
      confetti({
        particleCount: 70,
        spread: 60,
        origin: { y: 0.7 },
      });
    } catch (err) {
      console.error("Export zip error:", err);
      alert("打包工程包时遇到问题，请重试");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <section
      id="page-engineering"
      className="flex-1 flex flex-col bg-[#f8fafc] min-h-[calc(100vh-60px)]"
    >
      {/* SUB HEADER BAR */}
      <div className="bg-white border-b border-slate-200 px-6 py-3 flex flex-wrap items-center justify-between gap-3 shadow-2xs">
        <div className="flex items-center space-x-3">
          <div className="p-1.5 bg-indigo-50 text-indigo-600 rounded-lg">
            <FolderGit2 className="w-5 h-5" />
          </div>
          <span className="font-bold text-slate-800 text-base">项目工程工作台</span>
          <span className="bg-emerald-50 text-emerald-600 text-xs px-2.5 py-0.5 rounded-full font-semibold border border-emerald-200 flex items-center shadow-xs">
            <Check className="w-3.5 h-3.5 mr-1" />
            <span>方案已确认 {project.version}</span>
          </span>
        </div>

        <div className="flex items-center space-x-3">
          <button
            id="btn-back-to-workbench"
            onClick={onBackToWorkbench}
            className="bg-white hover:bg-slate-50 active:bg-slate-100 text-slate-700 border border-slate-200 text-xs font-semibold px-4 py-2 rounded-lg transition flex items-center shadow-xs cursor-pointer"
          >
            <RotateCcw className="w-3.5 h-3.5 mr-1.5" />
            <span>返回修改方案</span>
          </button>
          <button
            id="btn-export-package"
            onClick={handleExportZip}
            disabled={isExporting}
            className="bg-emerald-500 hover:bg-emerald-600 active:scale-98 text-white text-xs font-semibold px-4 py-2 rounded-lg transition flex items-center shadow-md shadow-emerald-500/20 disabled:opacity-75 cursor-pointer"
          >
            {isExporting ? (
              <>
                <div className="w-3.5 h-3.5 mr-1.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                <span>打包生成中...</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5 mr-1.5" />
                <span>导出完整工程包 (.zip)</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* MAIN CONTENT GRID */}
      <div className="flex-1 p-5 grid grid-cols-1 md:grid-cols-12 gap-5 max-w-[1600px] mx-auto w-full">
        {/* LEFT COLUMN: 3D MODEL & STATUS (col-span-4) */}
        <div className="md:col-span-4 flex flex-col space-y-4">
          <div className="bg-white p-5 rounded-2xl border border-slate-200/80 shadow-xs flex-1 flex flex-col justify-between">
            <div className="flex items-center justify-between mb-2">
              <h3 className="font-bold text-slate-800 text-sm">3D 结构与模组映射</h3>
              <span className="text-xs text-indigo-600 font-mono bg-indigo-50 px-2 py-0.5 rounded">
                CAD / STL 就绪
              </span>
            </div>

            {/* Visual Hardware Preview Container */}
            <div className="my-auto bg-gradient-to-b from-slate-50 to-indigo-50/40 rounded-xl p-6 flex flex-col items-center justify-center relative border border-slate-100 min-h-[260px]">
              {/* Responsive White Robot/Device Mockup */}
              <div className="w-44 h-48 bg-white rounded-[2.5rem] shadow-xl border-2 border-slate-100 flex flex-col items-center justify-center p-3 relative group transition hover:scale-102">
                {/* Screen */}
                <div className="w-32 h-24 bg-slate-900 rounded-2xl flex flex-col items-center justify-center relative overflow-hidden shadow-inner">
                  <div className="w-2 h-2 rounded-full bg-red-500 absolute top-2"></div>
                  <div className="flex space-x-5 mt-2">
                    <div className="w-3.5 h-3.5 bg-cyan-400 rounded-full animate-pulse shadow-[0_0_10px_#22d3ee]"></div>
                    <div className="w-3.5 h-3.5 bg-cyan-400 rounded-full animate-pulse shadow-[0_0_10px_#22d3ee]"></div>
                  </div>
                  <span className="text-[8px] text-slate-500 tracking-widest mt-2 font-mono">
                    OLED DISPLAY
                  </span>
                </div>
                {/* Base */}
                <div className="w-24 h-12 bg-slate-100 rounded-b-2xl mt-3 border-t border-slate-200 flex items-center justify-center">
                  <span className="text-[9px] text-slate-400 font-mono">ESP32 + LIPO</span>
                </div>
              </div>

              <div className="mt-4 bg-emerald-50 text-emerald-700 border border-emerald-200 text-xs px-3.5 py-1.5 rounded-full flex items-center font-medium shadow-2xs">
                <CheckCircle2 className="w-3.5 h-3.5 mr-1.5 text-emerald-500 shrink-0" />
                <span>3D 模型与 BOM 100% 对应</span>
              </div>
            </div>

            {/* Quick Actions Bar */}
            <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
              <span>预估总成单价</span>
              <span className="font-bold text-slate-800 text-sm font-mono">
                ¥{totalPrice.toFixed(2)}
              </span>
            </div>
          </div>

          {/* Engineering Archive Status */}
          <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-xs space-y-2">
            <div className="flex items-center space-x-2 text-indigo-600 font-bold text-xs">
              <Archive className="w-4 h-4" />
              <span>工程归档状态</span>
            </div>
            <p className="text-[11px] text-slate-500 leading-relaxed">
              生成的资料包含：CAD/STL 3D打印切片文件、电路接线图、固件源码与烧录脚本。
            </p>
            <div className="pt-2 grid grid-cols-2 gap-2 text-[11px]">
              <div className="bg-slate-50 p-2 rounded-lg border border-slate-100 text-slate-600">
                <div className="font-semibold text-slate-800">固件编译器</div>
                <div className="text-[10px] text-slate-400">ESP-IDF v5.1 / GCC</div>
              </div>
              <div className="bg-slate-50 p-2 rounded-lg border border-slate-100 text-slate-600">
                <div className="font-semibold text-slate-800">PCB 接口总线</div>
                <div className="text-[10px] text-slate-400">I2C / I2S / DVP 兼容</div>
              </div>
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: TABS & TABLES (col-span-8) */}
        <div className="md:col-span-8 bg-white rounded-2xl border border-slate-200/80 shadow-xs flex flex-col overflow-hidden">
          {/* TAB NAVIGATION */}
          <div className="border-b border-slate-200 px-6 pt-3 flex space-x-8 text-xs font-semibold overflow-x-auto">
            <button
              id="tab-btn-info"
              onClick={() => setActiveTab("info")}
              className={`pb-3 transition relative cursor-pointer ${
                activeTab === "info"
                  ? "border-b-2 border-indigo-600 text-indigo-600 font-bold"
                  : "text-slate-500 hover:text-slate-800"
              }`}
            >
              INFO (定义)
            </button>
            <button
              id="tab-btn-bom"
              onClick={() => setActiveTab("bom")}
              className={`pb-3 transition relative cursor-pointer ${
                activeTab === "bom"
                  ? "border-b-2 border-indigo-600 text-indigo-600 font-bold"
                  : "text-slate-500 hover:text-slate-800"
              }`}
            >
              PARTS / BOM (清单)
            </button>
            <button
              id="tab-btn-wiring"
              onClick={() => setActiveTab("wiring")}
              className={`pb-3 transition relative cursor-pointer ${
                activeTab === "wiring"
                  ? "border-b-2 border-indigo-600 text-indigo-600 font-bold"
                  : "text-slate-500 hover:text-slate-800"
              }`}
            >
              WIRING (电气接线)
            </button>
            <button
              id="tab-btn-mech"
              onClick={() => setActiveTab("mech")}
              className={`pb-3 transition relative cursor-pointer ${
                activeTab === "mech"
                  ? "border-b-2 border-indigo-600 text-indigo-600 font-bold"
                  : "text-slate-500 hover:text-slate-800"
              }`}
            >
              MECH (结构)
            </button>
            <button
              id="tab-btn-instructions"
              onClick={() => setActiveTab("instructions")}
              className={`pb-3 transition relative cursor-pointer ${
                activeTab === "instructions"
                  ? "border-b-2 border-indigo-600 text-indigo-600 font-bold"
                  : "text-slate-500 hover:text-slate-800"
              }`}
            >
              INSTRUCTIONS (交付说明)
            </button>
          </div>

          {/* TAB CONTENT CONTAINER */}
          <div className="p-6 flex-1 space-y-6 overflow-y-auto max-h-[640px]">
            {/* ================= TAB: BOM ================= */}
            {activeTab === "bom" && (
              <div className="space-y-4">
                <div className="flex flex-wrap justify-between items-center gap-2">
                  <div>
                    <h3 className="font-bold text-slate-800 text-sm">
                      完整硬件 BOM 清单 ({project.components.length} 项组件)
                    </h3>
                    <p className="text-xs text-slate-400 mt-0.5">
                      包含电路主控、音频接口、传感器、电池及机壳机械件
                    </p>
                  </div>
                  <div className="flex items-center space-x-2">
                    <span className="text-xs text-emerald-600 font-bold bg-emerald-50 px-2.5 py-1 rounded-md border border-emerald-200">
                      预估总单价：￥{totalPrice.toFixed(2)}
                    </span>
                  </div>
                </div>

                <div className="border border-slate-200 rounded-xl overflow-hidden shadow-2xs">
                  <table className="w-full text-left text-xs text-slate-600">
                    <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 font-semibold">
                      <tr>
                        <th className="py-2.5 px-4">编号</th>
                        <th className="py-2.5 px-4">模块名称</th>
                        <th className="py-2.5 px-4">规格型号</th>
                        <th className="py-2.5 px-4">用量</th>
                        <th className="py-2.5 px-4">接口/总线</th>
                        <th className="py-2.5 px-4">预估单价</th>
                        <th className="py-2.5 px-4">3D 关联</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {project.components.map((comp) => {
                        const isSelected = highlightedRow === comp.id;
                        return (
                          <tr
                            key={comp.id}
                            className={`transition ${
                              isSelected
                                ? "bg-indigo-50/70"
                                : "hover:bg-slate-50/60"
                            }`}
                          >
                            <td className="py-2.5 px-4 font-mono font-semibold text-slate-500">
                              {comp.id}
                            </td>
                            <td className="py-2.5 px-4 font-medium text-slate-800">
                              {comp.name}
                            </td>
                            <td className="py-2.5 px-4 font-mono text-[11px] text-slate-600">
                              {comp.model}
                            </td>
                            <td className="py-2.5 px-4 font-semibold text-slate-700">
                              {comp.quantity}
                            </td>
                            <td className="py-2.5 px-4">
                              <span className="bg-slate-100 text-slate-700 px-2 py-0.5 rounded text-[10px] font-mono font-medium">
                                {comp.bus}
                              </span>
                            </td>
                            <td className="py-2.5 px-4 font-semibold text-indigo-600 font-mono">
                              ¥{comp.price.toFixed(2)}
                            </td>
                            <td className="py-2.5 px-4">
                              <button
                                onClick={() => {
                                  setHighlightedRow(comp.id);
                                  if (onSelectHighlightKey && comp.highlightKey) {
                                    onSelectHighlightKey(comp.highlightKey);
                                  }
                                }}
                                className="text-indigo-600 hover:text-indigo-800 hover:underline cursor-pointer font-medium"
                              >
                                [查看高亮]
                              </button>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>

                {/* INSTRUCTIONS PREVIEW SNIPPET */}
                <div className="pt-2">
                  <h3 className="font-bold text-slate-800 text-sm mb-2.5">
                    INSTRUCTIONS Preview (烧录与装配摘要)
                  </h3>
                  <div className="bg-indigo-50/30 border border-indigo-100 rounded-xl p-4 space-y-3">
                    <div className="font-bold text-indigo-700 text-xs">
                      步骤 1: 固件烧录 (Firmware Flashing)
                    </div>
                    <p className="text-xs text-slate-500">
                      使用 Type-C 数据线连接主控板 M01，运行工程包内的自动烧录脚本：
                    </p>
                    <div className="bg-slate-900 text-slate-200 text-xs font-mono p-3 rounded-lg flex items-center justify-between shadow-inner">
                      <span className="truncate mr-2 font-mono">
                        {project.instructions.step1Flash}
                      </span>
                      <button
                        onClick={() => handleCopyCode(project.instructions.step1Flash)}
                        className="text-slate-400 hover:text-white transition p-1 rounded hover:bg-slate-800 shrink-0 cursor-pointer"
                        title="复制代码"
                      >
                        {copiedCode ? (
                          <CheckCheck className="w-4 h-4 text-emerald-400" />
                        ) : (
                          <Copy className="w-4 h-4" />
                        )}
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* ================= TAB: INFO ================= */}
            {activeTab === "info" && (
              <div className="space-y-6">
                <div>
                  <h3 className="font-bold text-slate-800 text-sm mb-1">
                    产品系统规格 (Specification)
                  </h3>
                  <p className="text-xs text-slate-500">
                    硬件电气规格、尺寸公差与无线通讯参数总览
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="bg-slate-50/70 p-4 rounded-xl border border-slate-200/80 space-y-2.5">
                    <h4 className="font-bold text-xs text-slate-800 flex items-center">
                      <Cpu className="w-3.5 h-3.5 mr-1.5 text-indigo-600" />
                      计算与控制核心
                    </h4>
                    <div className="text-xs space-y-1.5 text-slate-600">
                      <div className="flex justify-between">
                        <span className="text-slate-400">MCU:</span>
                        <span className="font-semibold text-slate-800">{project.specs.mcu}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">固件系统:</span>
                        <span className="font-mono text-slate-800">{project.specs.firmware}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">网络连接:</span>
                        <span className="font-medium text-slate-800">
                          {project.specs.connectivity}
                        </span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-slate-50/70 p-4 rounded-xl border border-slate-200/80 space-y-2.5">
                    <h4 className="font-bold text-xs text-slate-800 flex items-center">
                      <Layers className="w-3.5 h-3.5 mr-1.5 text-emerald-600" />
                      外形与供电方案
                    </h4>
                    <div className="text-xs space-y-1.5 text-slate-600">
                      <div className="flex justify-between">
                        <span className="text-slate-400">外形尺寸:</span>
                        <span className="font-mono text-slate-800">
                          {project.specs.dimensions}
                        </span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">整机重量:</span>
                        <span className="font-mono text-slate-800">{project.specs.weight}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">内置电池:</span>
                        <span className="font-medium text-slate-800">{project.specs.battery}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-slate-400">供电接口:</span>
                        <span className="font-medium text-slate-800">
                          {project.specs.powerSupply}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Cloud & OTA */}
                <div className="bg-indigo-50/30 border border-indigo-100 rounded-xl p-4 space-y-2">
                  <div className="font-bold text-indigo-800 text-xs flex items-center">
                    <ExternalLink className="w-3.5 h-3.5 mr-1.5 text-indigo-600" />
                    云端造物 V Cloud 交互协议
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    设备出厂固件已集成标准 WebSocket 客户端与 TLS 1.3 传输加密。开机配网后将自动与云端大模型中继服务器握手，无需用户自行搭建后端即可体验流式语音问答与设备控制。
                  </p>
                </div>
              </div>
            )}

            {/* ================= TAB: WIRING ================= */}
            {activeTab === "wiring" && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-bold text-slate-800 text-sm mb-1">
                    电气接线与引脚定义 (Pinout & Wiring Diagram)
                  </h3>
                  <p className="text-xs text-slate-500">
                    ESP32 主控管脚分配、上拉电阻及总线拓扑关系表
                  </p>
                </div>

                <div className="border border-slate-200 rounded-xl overflow-hidden shadow-2xs">
                  <table className="w-full text-left text-xs text-slate-600">
                    <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 font-semibold">
                      <tr>
                        <th className="py-2.5 px-4">主控引脚 (MCU Pin)</th>
                        <th className="py-2.5 px-4">外设模块</th>
                        <th className="py-2.5 px-4">目标引脚</th>
                        <th className="py-2.5 px-4">信号类型</th>
                        <th className="py-2.5 px-4">接线与电路要点</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {project.wiring.map((w, idx) => (
                        <tr key={idx} className="hover:bg-slate-50/60">
                          <td className="py-2.5 px-4 font-mono font-semibold text-indigo-700">
                            {w.fromPin}
                          </td>
                          <td className="py-2.5 px-4 font-medium text-slate-800">
                            {w.toComponent}
                          </td>
                          <td className="py-2.5 px-4 font-mono text-slate-600">{w.toPin}</td>
                          <td className="py-2.5 px-4">
                            <span
                              className={`px-2 py-0.5 rounded text-[10px] font-mono font-semibold ${
                                w.signalType === "I2C"
                                  ? "bg-blue-100 text-blue-800"
                                  : w.signalType === "I2S"
                                  ? "bg-indigo-100 text-indigo-800"
                                  : w.signalType === "Power"
                                  ? "bg-amber-100 text-amber-800"
                                  : "bg-slate-100 text-slate-800"
                              }`}
                            >
                              {w.signalType}
                            </span>
                          </td>
                          <td className="py-2.5 px-4 text-slate-500 text-[11px]">{w.note}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <div className="bg-amber-50/60 border border-amber-200 rounded-xl p-3.5 text-xs text-amber-800">
                  <div className="font-semibold mb-1">接线安全注意:</div>
                  <ul className="list-disc list-inside space-y-0.5 text-amber-700 text-[11px]">
                    <li>ESP32-S3 所有 GPIO 逻辑电平为 3.3V，严禁直接连接 5V 电平信号。</li>
                    <li>
                      I2S 音频功放（MAX98357A）必须并联 470μF 电解电容，防止大动态音量导致主控拉低复位。
                    </li>
                  </ul>
                </div>
              </div>
            )}

            {/* ================= TAB: MECH ================= */}
            {activeTab === "mech" && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-bold text-slate-800 text-sm mb-1">
                    结构件与 3D 打印加工清单 (Mechanical & Slicing)
                  </h3>
                  <p className="text-xs text-slate-500">
                    可直接发送给 3D 打印服务商或使用个人 3D 打印机切片成型
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {project.mechParts.map((part, idx) => (
                    <div
                      key={idx}
                      className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-2xs space-y-2"
                    >
                      <div className="flex justify-between items-start">
                        <h4 className="font-bold text-xs text-slate-800">{part.name}</h4>
                        <span className="text-[10px] font-semibold bg-indigo-50 text-indigo-600 px-2 py-0.5 rounded">
                          数量: x{part.count}
                        </span>
                      </div>
                      <div className="text-xs space-y-1 text-slate-600">
                        <div className="flex justify-between text-[11px]">
                          <span className="text-slate-400">推荐材料:</span>
                          <span className="font-medium text-slate-700">{part.material}</span>
                        </div>
                        <div className="flex justify-between text-[11px]">
                          <span className="text-slate-400">工艺参数:</span>
                          <span className="font-mono text-slate-700">{part.method}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Slicing Advice */}
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-200/80 space-y-2 text-xs text-slate-600">
                  <div className="font-bold text-slate-800">3D 打印切片通用建议:</div>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-[11px]">
                    <div className="bg-white p-2 rounded-lg border border-slate-100">
                      <div className="text-slate-400">建议层高</div>
                      <div className="font-bold text-slate-800 font-mono">0.16mm - 0.20mm</div>
                    </div>
                    <div className="bg-white p-2 rounded-lg border border-slate-100">
                      <div className="text-slate-400">填充密度</div>
                      <div className="font-bold text-slate-800 font-mono">25% 陀螺线填充</div>
                    </div>
                    <div className="bg-white p-2 rounded-lg border border-slate-100">
                      <div className="text-slate-400">壁厚圈数</div>
                      <div className="font-bold text-slate-800 font-mono">3 圈 (1.2mm)</div>
                    </div>
                    <div className="bg-white p-2 rounded-lg border border-slate-100">
                      <div className="text-slate-400">支撑类型</div>
                      <div className="font-bold text-slate-800 font-mono">树状支撑 (易拆)</div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* ================= TAB: INSTRUCTIONS ================= */}
            {activeTab === "instructions" && (
              <div className="space-y-6">
                <div>
                  <h3 className="font-bold text-slate-800 text-sm mb-1">
                    硬件装配与交付说明 (Assembly & Flashing Guide)
                  </h3>
                  <p className="text-xs text-slate-500">
                    按照以下 4 个标准步骤，从零件组装到最终联调测试
                  </p>
                </div>

                {/* STEP 1 */}
                <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-2xs space-y-2">
                  <div className="flex items-center space-x-2">
                    <span className="w-5 h-5 bg-indigo-600 text-white rounded-full flex items-center justify-center text-xs font-bold">
                      1
                    </span>
                    <h4 className="font-bold text-xs text-slate-800">
                      固件烧录 (Firmware Flashing)
                    </h4>
                  </div>
                  <p className="text-xs text-slate-500">{project.instructions.flashGuide}</p>
                  <div className="bg-slate-900 text-slate-200 text-xs font-mono p-3 rounded-lg flex items-center justify-between shadow-inner">
                    <span className="truncate mr-2 font-mono">
                      {project.instructions.step1Flash}
                    </span>
                    <button
                      onClick={() => handleCopyCode(project.instructions.step1Flash)}
                      className="text-slate-400 hover:text-white transition p-1 rounded hover:bg-slate-800 shrink-0 cursor-pointer"
                      title="复制代码"
                    >
                      {copiedCode ? (
                        <CheckCheck className="w-4 h-4 text-emerald-400" />
                      ) : (
                        <Copy className="w-4 h-4" />
                      )}
                    </button>
                  </div>
                </div>

                {/* STEP 2 */}
                <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-2xs space-y-2">
                  <div className="flex items-center space-x-2">
                    <span className="w-5 h-5 bg-indigo-600 text-white rounded-full flex items-center justify-center text-xs font-bold">
                      2
                    </span>
                    <h4 className="font-bold text-xs text-slate-800">硬件组装与接线</h4>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed bg-slate-50 p-3 rounded-lg border border-slate-100">
                    {project.instructions.assemblyGuide}
                  </p>
                </div>

                {/* STEP 3 */}
                <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-2xs space-y-2">
                  <div className="flex items-center space-x-2">
                    <span className="w-5 h-5 bg-indigo-600 text-white rounded-full flex items-center justify-center text-xs font-bold">
                      3
                    </span>
                    <h4 className="font-bold text-xs text-slate-800">Wi-Fi 网络配网</h4>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    {project.instructions.wifiConfig}
                  </p>
                </div>

                {/* STEP 4 */}
                <div className="bg-white p-4 rounded-xl border border-slate-200/80 shadow-2xs space-y-2">
                  <div className="flex items-center space-x-2">
                    <span className="w-5 h-5 bg-indigo-600 text-white rounded-full flex items-center justify-center text-xs font-bold">
                      4
                    </span>
                    <h4 className="font-bold text-xs text-slate-800">云端联调与出厂自检</h4>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    {project.instructions.cloudTesting}
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};
